### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: type "vector" does not exist

### ISSUE THREAD

**Issue by FFFro** [pgvector/pgvector-java#8]
Connection connection = sqlSession.getConnection();
            Statement setupStmt = connection.createStatement();
            setupStmt.executeUpdate("CREATE EXTENSION IF NOT EXISTS vector");
            PGvector.addVectorType(connection);
            PreparedStatement neighborStmt = connection.prepareStatement("SELECT * FROM crawler.doc_vector ORDER BY vectors <=> CAST(? AS vector) LIMIT 1");
            neighborStmt.setObject(1, new PGvector(convertToFloatArray(embedding)).getValue());
            ResultSet rs = neighborStmt.executeQuery();
throw the exception:
`
Caused by: org.postgresql.util.PSQLException: ERROR: type "vector" does not exist
  位置：66
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2675)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2365)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:355)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:490)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:408)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:167)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:119)
	at com.alibaba.druid.pool.DruidPooledPreparedStatement.executeQuery(DruidPooledPreparedStatement.java:213)
`

**Comment by FFFro** [comment]
the nspname is 'public', 
```
alter extension vector set schema crawler;thank you.
